<?php
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
namespace Swiftriver\Core;

require_once 'PHPUnit/Framework.php';

/**
 * Test class for ParserFactory.
 * Generated by PHPUnit on 2010-03-13 at 09:23:18.
 */
class EmailParserTest extends \PHPUnit_Framework_TestCase {
    /**
     * Include the SiSPS Setup
     */
    protected function setUp() {
        include_once(dirname(__FILE__)."/../../../../Setup.php");
    }

    /**
     * Tests that given the an array of parameters containing a
     * valid feedUrl, the RSSParser can correctly extract an
     * array of content Items.
     */
    public function testThatTheEmailParserCanExtractContentItemsFromEmailDetails() {
        $parser = new \Swiftriver\Core\Modules\SiSPS\Parsers\TwitterSearchParser();
        $content = $parser->GetAndParse(
                array(
                    "email_ssl" => false,
                    "email_servertype" => "imap",
                    "email_host" => "imap.gmail.com",
                    "email_port" => "993",
                    "email_username" => "ushahidi.swift@gmail.com",
                    "email_password" => "swift.river"
                ),
                mktime(0, 0, 0, 1, 1, 1970)
        );
        $this->assertEquals(true, isset($content));
        $this->assertEquals(true, is_array($content));
        foreach($content as $item) {
            $this->assertEquals(true, isset($item));
            $title = $item->title;
            $link = $item->link;
            $text = reset($item->text);
            $this->assertEquals(true, isset($text->title));
            $this->assertEquals(true, isset($link));
            $this->assertEquals(true, isset($text->text));
            $this->assertEquals(true, is_array($text->text));
        }
    }
}
?>
